"""empty message

Revision ID: 8fbd009a8087
Revises: a5cffa318ac2
Create Date: 2026-03-23 11:35:26.455494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbd009a8087'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('poblation', sa.String(length=30), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('dimensions', sa.String(length=30), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=30), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('user_name')

    op.drop_table('vehicles')
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('favorites')
    # ### end Alembic commands ###
